plugins:
  rubocop:
    enabled: false
    checks:
        #Rubocop/Metrics/ClassLength:
        #  enabled: false
        Rubocop/Style/StringLiterals:
          enabled: false
        Rubocop/Layout/LeadingCommentSpace:
          enabled: false
        Rubocop/Layout/EmptyLinesAroundClassBody:
          enabled: false
