sudo: false
language: ruby
rvm:
  - 2.2.5
before_install: gem install bundler -v 1.16.0
env:
  global:
    - CC_TEST_REPORTER_ID=8f424c1882aec9c7bf8f1975801bf5913caa16ca31ecf859b2b4bd839bb362ca
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
